services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reserve-beach-node
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}